FROM jenkins/jenkins:lts

USER root

# Install Docker CLI, Python3, pip, and curl
RUN apt-get update && \
    apt-get install -y docker.io python3 python3-pip python3-venv curl && \
    apt-get clean

# Install kubectl
RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && \
    chmod +x ./kubectl && \
    mv ./kubectl /usr/local/bin/kubectl

# Allow jenkins user to run docker
RUN usermod -aG docker jenkins

USER jenkins